### ISSUE TITLE
Rails 6.1 support

### ISSUE THREAD

**Issue by garytaylor** [nulldb/nulldb#105]
Hello,
  I am using this gem in my project for 'form objects' and I would like to upgrade to rails 6.1 - however, this gem seems to be holding back that upgrade.

Is the reason for not supporting 6.1 simply because it hasn't been done yet - or do the 6.1 changes mean the end of the road for this gem in newer rails projects ?

Thanks

Gary

**Comment by cabello** [comment]
Implemented by https://github.com/nulldb/nulldb/pull/106
