### ISSUE TITLE
Fail to load schema with long name index

### ISSUE THREAD

**Issue by rjherrera** [nulldb/nulldb#107]
Hi there! I was setting up my project with nulldb and I ended up with a weird problem after I specified the schema to use.

What happens when executing rspec is that it throws this error:

```Index name '...' on table '...' is too long; the limit is 63 characters;```

I tried without the schema before getting that error, but it also failed, telling me it wasn't able to find the foreign_keys  (seems reasonable, given that there was no schema), so I specified it.

For the record I'm connecting using `establish_connection(adapter: :nulldb, schema: 'db/external_schema.rb')`

I also read the bug you mention in the readme regarding using nulldb with rspec but it seems unrelated, and I use specs with the normal database and the external one.

Any help you can give me is greatly appreciated!

Thank you!

**Comment by rjherrera** [comment]
Hi there! I ended up removing the tests that used the external database I was trying to "mock" with nulldb. Sadly I could not find an easy workaround. I tried again today with the new release but it still happens. 

Maybe something could be done while reading the schema, like renaming those indexes to fit the limit, but that sounds a bit too hacky haha.

In my case it was not critical as we could opt to only test flows that involved models in the internal database, and it was a quick prototype, but for a more robust solution, it would be nice to have nulldb working.

**Comment by cabello** [comment]
What database are you using? PostgreSQL has a limit of 63 chars so you could have similar issues in production https://til.hashrocket.com/posts/8f87c65a0a-postgresqls-max-identifier-length-is-63-bytes

**Comment by rjherrera** [comment]
In that particular project it is MySQL,  that's why I'm seeing this problem I guess, but you are right about the limit!

**Comment by cabello** [comment]
Closing this for now, @rjherrera feel free to reopen if needed.
