### ISSUE TITLE
Rails 7.0 support

### ISSUE THREAD

**Issue by rjschof** [nulldb/nulldb#114]
Rails 7.0 was released on December 15, 2021. 

Can we get an update released for Rails 7.0.0?

**Comment by rjschof** [comment]
#113

**Comment by cabello** [comment]
Hi @rjschof I see the tests were passing for alpha and for the main release after I ran your PR. Am I missing something, do you need a new release in order to install with Rails 7?

**Comment by rjschof** [comment]
I think this is actually a duplicate of #113. I'll close it. Thanks!
