### ISSUE TITLE
Missing 1.0.0 and 1.0.1

### ISSUE THREAD

**Issue by ekohl** [nulldb/nulldb#126]
When I look at the repository I don't see `v1.0.0` in https://github.com/nulldb/nulldb/releases. Another thing that looks off is that https://github.com/nulldb/nulldb/blob/master/lib/nulldb/version.rb still shows `0.9.0` in master. Then `CHANGES.md` is also stuck at 1.0.1.

I'd like this to all be consistent.

**Comment by cabello** [comment]
* v1.0.1 was released shortly after v1.0.1 so only 1.0.1 got the release entry in the releases page
* you were correct to point the version and changes was outdated, it was missing a push, done
