### ISSUE TITLE
rails4 tests fail when using rake

### ISSUE THREAD

**Issue by erkki** [nulldb/nulldb#51]
in rails4 apps tests fail when using rake because of the re-defined schema#define method. Removing the re-define makes everything work. 

```
module ActiveRecord
  # Just make sure you have the latest version of your schema
  class Schema < Migration
    def self.define(info={}, &block)
      instance_eval(&block)
    end
  end
end
```

The interaction here is a bit complex:
1) rake test/rspec
2) rake tasks run which are supposed to empty + reinitialize the schema (in original adapter context)
3) tests run in nulldb context after the connection is reinitialized in test_helper.rb

It's the 2nd step which fails due to the re-define (which should actually initialize the schema_migrations table).

it may also be the case 3) is initializing nulldb too late and that's something which should be changed

It looks like at some point nulldb patched rails raketasks to avoid the cleanup+reinitialize cycle but that's not working anymore.

```
# Sadly, we have to monkeypatch Rake because all of the Rails database tasks are
# hardcoded for specific adapters, with no extension points (!)
Rake::TaskManager.class_eval do
  def remove_task(task_name)
    @tasks.delete(task_name.to_s)
  end
end

def remove_task(task_name)
  Rake.application.remove_task(task_name)
end

def wrap_task(task_name, &wrapper)
  wrapped_task = Rake::Task[task_name]
  remove_task(Rake::Task.scope_name(Rake.application.current_scope,
                                    task_name))
  task(task_name) do
    wrapper.call(wrapped_task)
  end
end

namespace :db do
  namespace :test do
    wrap_task :purge do |wrapped_task|
      if ActiveRecord::Base.configurations["test"]["adapter"] == "nulldb"
        # NO-OP
      else
        wrapped_task.invoke
      end
    end
  end
end
```

It seems to me both the modified schema#define and raketask patches should go away.

There doesn't seem to be a good way to test these integrations right now though so it's hard to guarantee backwards compatibility. Maybe some sorts of rails specific test harness should be added (even if in separate repo)?

Any thoughts so far?

**Comment by onyxraven** [comment]
@erkki have you forked this and removed those patches?  I'm running into the same issues in rails 4.2

**Comment by erkki** [comment]
Nope, no fork. Not using nulldb at the moment.
