### ISSUE TITLE
NullDB interferes with ActiveRecord::Migration.maintain_test_schema! in Rails 4.2.0

### ISSUE THREAD

**Issue by floehopper** [nulldb/nulldb#58]
We use `ActiveRecord::Migration.maintain_test_schema!` in our spec helper so that we don't need to remember to run `rake db:test:prepare` as [recommended in the Rails v4.1 release notes](https://github.com/rails/rails/blob/7ba24831d7f809d54e88607db8f7d21780efbdfb/guides/source/4_1_release_notes.md#notable-changes). However, NullDB appears to interfere with this in that ActiveRecord realises that the database is not up-to-date, but it does not manage to migrate the database as I would expect. I haven't got to the bottom of why this happens, but I have worked around it by setting `require: false` for the `activerecord-nulldb-adapter` gem in the `Gemfile` and then explicitly requiring it **after** the call to `ActiveRecord::Migration.maintain_test_schema!` in the spec helper.

Does anyone know why this problem is occurring and/or a better way to work around it? Thanks.

**Comment by reiz** [comment]
+1

**Comment by patrickdet** [comment]
+1

**Comment by ariera** [comment]
+1

**Comment by n3bulous** [comment]
+1

http://stackoverflow.com/questions/20106684/rake-dbschemaload-not-populating-schema-migrations-table


> So the end result was that another developer had installed activerecord-nulldb-adapter, which monkey patches ActiveRecord::Schema.define and doesn't run initialize_schema_migrations_table() or assume_migrated_up_version(). I uninstalled the gem, ran my db:schema:load just fine.

**Comment by mnoack** [comment]
I'm happy to accept pull requests if someone can write a test for it.

**Comment by edwardmp** [comment]
+1

**Comment by edwardmp** [comment]
I have to stress this is a pretty annoying issue, and I frequently forget it's caused by nulldb. Basically any time you perform a migration you will need to completely reset & recreate your test database
