### ISSUE TITLE
Is it safe to use in production?

### ISSUE THREAD

**Issue by collimarco** [nulldb/nulldb#67]
I have some Sidekiq workers that don't need and don't use the database.

However I have discovered that calling `Model.new` (when model inherits from ActiveRecord::Base) produces a call to the database (I am wondering why Rails doesn't use the `schema.rb` directly!?) and this establishes an unwanted connection.

Can I use this gem in production to prevent that connection or there are any security/stability/performance issues?

**Comment by mnoack** [comment]
It's certainly not the intended use case of nulldb, which is meant to make testing models easier. There's likely another way of solving your problem such as working out why you need to call new, and if a plain old ruby object (rather than active record class) could be used to manage your object.
