### ISSUE TITLE
Enable Travis

### ISSUE THREAD

**Issue by mnoack** [nulldb/nulldb#74]
@nulldb/team-nulldb 

Travis wasn't working on a recent PR (I was expecting it to show in the PR)

I went to travis (https://travis-ci.org/nulldb/nulldb) and got:
-----------------------------------------
This is not an active repository

You don't have sufficient rights to enable this repo on Travis.
Please contact the admin to enable it or to receive admin rights yourself.
-----------------------------------------

Who is an admin in our team, and can they have a look at that page (they probably just need to click one button)

**Comment by isaacsanders** [comment]
Done
