### ISSUE TITLE
NoMethodError: undefined method `json' for #<ActiveRecord::ConnectionAdapters::TableDefinition>

### ISSUE THREAD

**Issue by awesomescot** [nulldb/nulldb#81]
Maybe I'm doing something wrong but it seems that json columns aren't supported?  I'm trying to precompile assets similar to this tutorial http://blog.zeit.io/use-a-fake-db-adapter-to-play-nice-with-rails-assets-precompilation/

I'm getting the title error when loading rails for the precompile.  Here is a stack trace:
```
DB_ADAPTER=nulldb bundle exec rake assets:precompile
Exception raised while loading rollout defaults: getaddrinfo: nodename nor servname provided, or not known
rake aborted!
NoMethodError: undefined method `json' for #<ActiveRecord::ConnectionAdapters::TableDefinition:0x00007ffefb564440>
db/schema.rb:33:in `block (2 levels) in <top (required)>'
/Users/scot/.rvm/gems/ruby-2.4.2@feyonce/gems/activerecord-nulldb-adapter-0.3.8/lib/active_record/connection_adapters/nulldb_adapter/core.rb:64:in `create_table'
/Users/scot/.rvm/gems/ruby-2.4.2@feyonce/gems/activerecord-4.2.10/lib/active_record/migration.rb:665:in `block in method_missing'
/Users/scot/.rvm/gems/ruby-2.4.2@feyonce/gems/activerecord-4.2.10/lib/active_record/migration.rb:634:in `block in say_with_time'
/Users/scot/.rvm/gems/ruby-2.4.2@feyonce/gems/activerecord-4.2.10/lib/active_record/migration.rb:634:in `say_with_time'
/Users/scot/.rvm/gems/ruby-2.4.2@feyonce/gems/activerecord-4.2.10/lib/active_record/migration.rb:654:in `method_missing'
/Users/scot/.rvm/gems/ruby-2.4.2@feyonce/gems/activerecord-4.2.10/lib/active_record/migration.rb:416:in `method_missing'
/Users/scot/git/ironboard/db/schema.rb:24:in `block in <top (required)>'
/Users/scot/.rvm/gems/ruby-2.4.2@feyonce/gems/activerecord-nulldb-adapter-0.3.8/lib/nulldb/extensions.rb:39:in `instance_eval'
/Users/scot/.rvm/gems/ruby-2.4.2@feyonce/gems/activerecord-nulldb-adapter-0.3.8/lib/nulldb/extensions.rb:39:in `define'
/Users/scot/git/ironboard/db/schema.rb:14:in `<top (required)>'
/Users/scot/.rvm/gems/ruby-2.4.2@feyonce/gems/activerecord-nulldb-adapter-0.3.8/lib/active_record/connection_adapters/nulldb_adapter/core.rb:137:in `load'
/Users/scot/.rvm/gems/ruby-2.4.2@feyonce/gems/activerecord-nulldb-adapter-0.3.8/lib/active_record/connection_adapters/nulldb_adapter/core.rb:137:in `columns'
```
Line 33 of schema.rb is 
```
create_table "activity_feed_events", force: :cascade do |t|
...
33:    t.json     "data",           null: false
...
  end
```

Let me know if you'd like more information or if there is something I'm doing wrong.

Thanks.

**Comment by mnoack** [comment]
I've only took over maintaining this gem so I'm not familiar with every feature. I would imagine json columns aren't used much therefore aren't yet implemented in nulldb.

I welcome any PR's to add this feature :)

**Comment by michaelgpearce** [comment]
I had the same problem with `json` columns. I created a PR that allows the `TableDefinition` to be configured. Not sure if this is the best solution, but looks to work if you establish the connection with something like:

```ruby
ActiveRecord::Base.establish_connection :adapter => :nulldb, :table_definition_class_name => 'ActiveRecord::ConnectionAdapters::PostgreSQL::TableDefinition'
```

**Comment by harrisong** [comment]
@michaelgpearce thanks for your [PR](https://github.com/nulldb/nulldb/pull/82), appreciate the effort for that. Before that got merged, I got a temporary solution which works well with my rspec tests, so far... https://gist.github.com/harrisong/76b04cd5bbab029f1e73a9eacaa6e8ad

**Comment by mnoack** [comment]
@harrisong That PR is now merged. If people are happy with how it's working for a few days. I'm happy to cut a release.

**Comment by wstewartii** [comment]
Has a release been made for this?

**Comment by tomaszganski** [comment]
For someone who is looking for how to set up custom table_definition_class_name during rails precompilation 

`
# ../lib/tasks/before_assets_precompile.rake

task :before_assets_precompile do
  ActiveRecord::Base.establish_connection :adapter => :nulldb, :table_definition_class_name => 
  'ActiveRecord::ConnectionAdapters::PostgreSQL::TableDefinition'
end

# every time you execute 'rake assets:precompile'
# run 'before_assets_precompile' first
Rake::Task['assets:precompile'].enhance ['before_assets_precompile']
`

Remark: in database.yml you keep using postgres database.
