### ISSUE TITLE
Rake tasks not supported by 'nulldb' adapter

### ISSUE THREAD

**Issue by wellington1993** [nulldb/nulldb#83]
Hi, 

I got this error when I try to run:` rails test`
`ActiveRecord::Tasks::DatabaseNotSupported: Rake tasks not supported by 'nulldb' adapter`

Full error:
```
rails aborted!
ActiveRecord::Tasks::DatabaseNotSupported: Rake tasks not supported by 'nulldb' adapter
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:test:load => db:test:purge
(See full trace by running task with --trace)
Migrations are pending. To resolve this issue, run:

        bin/rails db:migrate RAILS_ENV=test
```
But if I try do run: `rails db:migrate RAILS_ENV=test` I got this another error:
```
== 20xx0xxx020xxx ChangeNameColumnX: migrating =============================
-- rename_column(:mytable, :x, :y)
rails aborted!
NotImplementedError: rename_column is not implemented
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```
Thanks!

**Comment by kzcat** [comment]
@wellington1993 
I had the same probrem and fixed it with
`rm db/migrate/*`

**Comment by ldipenti** [comment]
I'm getting the same issue when running "rake db:test:purge" upgrading from rails 4.2.11 to 5.0.7.2

**Comment by wellington1993** [comment]
@kzcat I suppose the null db is for test the application without change the migrate folder directory and the respective archives. It's strange to me test removing the migrate files.

**Comment by ldipenti** [comment]
@wellington1993 Which version of rails are you using? I believe nulldb isn't compatible with 5.x, it was working ok with 4.2 on my case.

**Comment by wellington1993** [comment]
@ldipenti My Ruby projects are 5.x or more. Maybe is that the problem.

**Comment by ldipenti** [comment]
@wellington1993 FYI: The pending PR helped me fix the issue, please take a look at https://github.com/nulldb/nulldb/pull/88 (I had to make an additional change mentioned on the PR)

**Comment by cabello** [comment]
Solved! 😄
