### ISSUE TITLE
JSONB fields not supported?

### ISSUE THREAD

**Issue by BreahnaDavid** [nulldb/nulldb#84]
undefined method `jsonb' for #<ActiveRecord::ConnectionAdapters::TableDefinition:0x000000096462f8>
tried it today, and got this issue

**Comment by itsmechlark** [comment]
Hi @BreahnaDavid, I was able to make it work using the patch below: 

```
if ENV['ENABLE_NULL_DB']
  begin
    require 'activerecord-nulldb-adapter'
    require 'active_record/connection_adapters/nulldb_adapter/table_definition'
    require 'active_record/connection_adapters/postgresql/schema_definitions'

    ActiveRecord::ConnectionAdapters::NullDBAdapter.send(:remove_const, 'TableDefinition')
    ActiveRecord::ConnectionAdapters::NullDBAdapter.const_set('TableDefinition', ActiveRecord::ConnectionAdapters::PostgreSQL::TableDefinition)
  rescue StandardError => e
    STDERR.put "#{e} failed to require activerecord-nulldb-adapter"
  end
end
```

**Comment by jeremywadsack** [comment]
@itsmechlark Thanks for sharing that patch.

I modified your conditional as follows to be less environment specific:

```
if Rails.configuration.database_configuration[Rails.env]["adapter"] == "nulldb"
```

I'm not part of this project, but it seems this might make a good fix to bake into `ActiveRecord::ConnectionAdapters::NullDBAdapter.TableDefinition`. Would you want to open a PR?

**Comment by mnoack** [comment]
If people have a reasonable Pull Request I am happy to merge it in. Key thing is ideally it won't affect other users (e.g. non postgres) negatively and has some kind of testing ideally around it (otherwise bugs can be re-introduced)

**Comment by JelF** [comment]
I used that patch, but got following error:
`ArgumentError: Unknown type :jsonb`
From `gems/activemodel-5.2.3/lib/active_model/type/registry.rb:22:in `lookup'`
